set rtp+=~/.vim/bundle/Vundle.vim

set expandtab
set smartindent
set smarttab
set hidden
set shiftwidth=2
set hlsearch
set incsearch
set laststatus=2
set ruler
set backupdir=./.backup,/tmp
set directory=./.backup,/tmp
set modeline

" Show tab and trailing space
set list listchars=tab:→\ ,trail:·
set list

" auto indent html
let g:html_indent_inctags = "html,head,body,div,a,nav,ul,ol,dl,li,table,thead,tbody,tr,th,td,blockquote,select,form,option,optgroup,fieldset,legend,label,header,section,aside,footer,figure,video,span,p,g,svg"
filetype plugin indent on
